runmode: debug
# test release
addr: :8080
name: apiserver
url: http://127.0.0.1:8080
max_ping_count: 2 # pingServer次数

log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: logs/log.log
  log_format_text: false
  rollingPolicy: size # size, daily
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7

db:
  name: db_apiserver
  addr: 192.168.4.250:3305
  username: root
  password: 123456

docker_db:
  name: db_apiserver
  addr: 192.168.4.250:3305
  username: root
  password: 123456